### ISSUE TITLE
uninitialized constant Profile::PROFILE_FLAG_FELLOW (NameError)

### ISSUE THREAD

**Issue by LucianU** [code4romania/volunt-app#40]
Full traceback
```ruby
/www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:270:in `const_get': uninitialized constant Profile::PROFILE_FLAG_FELLOW (NameError)
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:270:in `block in constantize'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:266:in `each'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:266:in `inject'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:266:in `constantize'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
        from /www/comunitate.code4.ro/app/controllers/concerns/profiles_controller_concern.rb:181:in `profile_controller'
        from /www/comunitate.code4.ro/app/controllers/fellows_controller.rb:4:in `<class:FellowsController>'
        from /www/comunitate.code4.ro/app/controllers/fellows_controller.rb:1:in `<top (required)>'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concurrency/share_lock.rb:117:in `exclusive'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:11:in `loading'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:475:in `each'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:475:in `block in eager_load!'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:473:in `each'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:473:in `eager_load!'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:354:in `eager_load!'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:59:in `each'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
        from /www/comunitate.code4.ro/config/environment.rb:5:in `<top (required)>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
        from config.ru:in `new'
        from config.ru:in `<main>'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:315:in `load_rackup'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:243:in `app'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/runner.rb:127:in `load_and_bind'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/single.rb:85:in `run'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/bin/puma:22:in `load'
        from /www/comunitate.code4.ro/.bundle/ruby/2.3.0/bin/puma:22:in `<main>'
```

**Comment by vitaliel** [comment]
@LucianU noi nu mai avem app/controllers/fellows_controller.rb, de unde este pe server?

**Comment by LucianU** [comment]
Da, era o problemă de deployment. Closing.
